/* FILE GENERATED BY THE 4U COMPILATOR */

#include<stdlib.h>
#include<stdbool.h>
#include<stdio.h>
#include<string.h>

int _esaisie;
char _csaisie;
char* _tsaisie;

int main(void){
	printf("%s","\nSomething:\n");
	printf("%s","Hello!\n");
	printf("%s","\nCreate variable:\n");
	long e_variable=0;
	char* t_variable=malloc(sizeof(char)*(strlen("Hi!")+1));
	if(t_variable==NULL){
	printf("\033[31m\033[01mERREUR\033[0m d'allocation memoire sur la variable t_variable !");
	exit(-1);
	}
	strcpy(t_variable,"Hi!");
	printf("%s",t_variable);
	printf("%s","\nIf:\n");
	if(5==5){
	printf("%ld",1);
	}else{
	printf("%s","Bug");
	}
	printf("%s","\n");
	if(true){
	printf("%ld",1);
	}
	printf("%s","\n");
	printf("%s","\n++ and --:\n");
	e_variable++;
	printf("%ld",e_variable);
	printf("%s","\n");
	e_variable--;
	printf("%ld",e_variable);
	printf("%s","\n");
	printf("%s","\nFor:\n");
	long e_a=1;
	long e_b=1;
	int i0;
	for(i0=0;i0<10;i0+=1){
	printf("%ld",e_a);
	printf("%s","\n");
	printf("%ld",e_b);
	printf("%s","\n");
	e_a+=e_b;
	e_b+=e_a;
	}
	printf("%s","\nWhile:\n");
	long e_i=0;
	while(e_i<=10){
	e_i+=2;
	printf("%ld",e_i);
	printf("%s","\n");
	}
	free(t_variable);
	return EXIT_SUCCESS;
}
