#include "4u.h"

unsigned int nb_boucle=0;

void debut_code_js(){
	fprintf(fichier, "<!DOCTYPE html>\n\
	<html>\n\
	\t<head>\n\
	\t\t<style>\n\
	\t\t\tkbd {\n\
	\t\t\t\tbackground-color: #eee;\n\
	\t\t\t\tborder-radius: 3px;\n\
	\t\t\t\tborder: 1px solid #b4b4b4;\n\
	\t\t\t\tbox-shadow: 0 1px 1px rgba(0, 0, 0, .2), 0 2px 0 0 rgba(255, 255, 255, .7) inset;\n\
	\t\t\t\tcolor: #333;\n\
	\t\t\t\tdisplay: inline-block;\n\
	\t\t\t\tfont-size: .85em;\n\
	\t\t\t\tfont-weight: 700;\n\
	\t\t\t\tline-height: 1;\n\
	\t\t\t\tpadding: 2px 4px;\n\
	\t\t\t\twhite-space: nowrap;\n\
	\t\t\t}\n\
	\t\t</style>\n\
	\t\t<meta charset=\"utf-8\">\n\
	\t\t<title>Programm</title>\n\
	\t</head>\n\
	\t<body>\n\
	\t\tPress <kbd>Ctrl</kbd>+<kbd>Maj</kbd>+<kbd>I</kbd> or <kbd>F12</kbd>\n\
	\t\t<script>\n\
	/* FILE GENERATED BY THE 4U COMPILATOR */\n\n");
	fprintf(fichier, "var _esaisie;\n");
	fprintf(fichier, "var _csaisie;\n");
	fprintf(fichier, "var _tsaisie;\n\n");
	fprintf(fichier, "function main(){\n");
}

void fin_code_js(){
	//fprintf(fichier, "\treturn EXIT_SUCCESS;\n");
	fprintf(fichier, "}\nmain();\nconsole.log(\"Enter \\\"main();\\\" in the console for re-execute\");\n\t\t</script>\n\t</body>\n</html>\n");
}

void genere_code_js(GNode* ast){
	if(ast){
		switch((long)ast->data){
			case SEQUENCE:
				genere_code_js(g_node_nth_child(ast,0));
				genere_code_js(g_node_nth_child(ast,1));
				break;
			case VARIABLE:
				fprintf(fichier,"%s",(char*)g_node_nth_child(ast,0)->data);
				break;
			case AFFECTATIONE:
				fprintf(fichier,"\tvar ");
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier,"=");
				genere_code_js(g_node_nth_child(ast,1));
				fprintf(fichier,";\n");
				break;
			case AFFECTATIONB:
				fprintf(fichier,"\tvar ");
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier,"=");
				genere_code_js(g_node_nth_child(ast,1));
				fprintf(fichier,";\n");
				break;
			case AFFECTATION:
				fprintf(fichier,"\t");
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier,"=");
				genere_code_js(g_node_nth_child(ast,1));
				fprintf(fichier,";\n");
				break;
			case AFFECTATION_PLUS:
				fprintf(fichier,"\t");
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier,"+=");
				genere_code_js(g_node_nth_child(ast,1));
				fprintf(fichier,";\n");
				break;
			case AFFECTATION_MOINS:
				fprintf(fichier,"\t");
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier,"-=");
				genere_code_js(g_node_nth_child(ast,1));
				fprintf(fichier,";\n");
				break;
			case AFFECTATION_MUL:
				fprintf(fichier,"\t");
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier,"*=");
				genere_code_js(g_node_nth_child(ast,1));
				fprintf(fichier,";\n");
				break;
			case AFFECTATION_DIV:
				fprintf(fichier,"\t");
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier,"/=");
				genere_code_js(g_node_nth_child(ast,1));
				fprintf(fichier,";\n");
				break;
			case AFFECTATION_MOD:
				fprintf(fichier,"\t");
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier,"%%=");
				genere_code_js(g_node_nth_child(ast,1));
				fprintf(fichier,";\n");
				break;
			case AFFECTATION_ET:
				fprintf(fichier,"\t");
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier,"&=");
				genere_code_js(g_node_nth_child(ast,1));
				fprintf(fichier,";\n");
				break;
			case AFFECTATION_OU:
				fprintf(fichier,"\t");
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier,"|=");
				genere_code_js(g_node_nth_child(ast,1));
				fprintf(fichier,";\n");
				break;
			case AFFECTATION_INCR:
				fprintf(fichier,"\t");
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier,"++;\n");
				break;
			case AFFECTATION_DECR:
				fprintf(fichier,"\t");
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier,"--;\n");
				break;
			case AFFICHAGEE:
				fprintf(fichier,"\tconsole.log(");
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier,");\n");
				break;
			case AFFICHAGEB:
				fprintf(fichier,"\tconsole.log(");
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier,"?\"true\":\"false\");\n");
				break;
			case ENTIER:
				fprintf(fichier,"%s",(char*)g_node_nth_child(ast,0)->data);
				break;
			case ADDITION:
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier,"+");
				genere_code_js(g_node_nth_child(ast,1));
				break;
			case SOUSTRACTION:
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier,"-");
				genere_code_js(g_node_nth_child(ast,1));
				break;
			case MULTIPLICATION:
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier,"*");
				genere_code_js(g_node_nth_child(ast,1));
				break;
			case DIVISION:
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier,"/");
				genere_code_js(g_node_nth_child(ast,1));
				break;
			case MODULO:
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier,"%%");
				genere_code_js(g_node_nth_child(ast,1));
				break;
			case INCREMENTATION:
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier,"+1");
				break;
			case DECREMENTATION:
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier,"-1");
				break;
			case VRAI:
				fprintf(fichier,"true");
				break;
			case FAUX:
				fprintf(fichier,"false");
				break;
			case ET:
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier,"&&");
				genere_code_js(g_node_nth_child(ast,1));
				break;
			case OU:
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier,"||");
				genere_code_js(g_node_nth_child(ast,1));
				break;
			case NON:
				fprintf(fichier,"!");
				genere_code_js(g_node_nth_child(ast,0));
				break;
			case EXPR_PAR:
				fprintf(fichier,"(");
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier,")");
				break;
			case EGALITE:
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier,"===");
				genere_code_js(g_node_nth_child(ast,1));
				break;
			case DIFFERENT:
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier,"!==");
				genere_code_js(g_node_nth_child(ast,1));
				break;
			case INFERIEUR:
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier,"<");
				genere_code_js(g_node_nth_child(ast,1));
				break;
			case SUPERIEUR:
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier,">");
				genere_code_js(g_node_nth_child(ast,1));
				break;
			case INFEGAL:
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier,"<=");
				genere_code_js(g_node_nth_child(ast,1));
				break;
			case SUPEGAL:
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier,">=");
				genere_code_js(g_node_nth_child(ast,1));
				break;
			case DANSII:
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier,">=");
				genere_code_js(g_node_nth_child(ast,1));
				fprintf(fichier,"&&");
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier,"<=");
				genere_code_js(g_node_nth_child(ast,2));
				break;
			case DANSEI:
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier,">");
				genere_code_js(g_node_nth_child(ast,1));
				fprintf(fichier,"&&");
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier,"<=");
				genere_code_js(g_node_nth_child(ast,2));
				break;
			case DANSIE:
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier,">=");
				genere_code_js(g_node_nth_child(ast,1));
				fprintf(fichier,"&&");
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier,"<");
				genere_code_js(g_node_nth_child(ast,2));
				break;
			case DANSEE:
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier,">");
				genere_code_js(g_node_nth_child(ast,1));
				fprintf(fichier,"&&");
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier,"<");
				genere_code_js(g_node_nth_child(ast,2));
				break;
			case NEGATIF:
				fprintf(fichier,"-");
				genere_code_js(g_node_nth_child(ast,0));
				break;
			case CONDITION_SI:
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier,"\n");
				break;
			case CONDITION_SI_SINON:
				genere_code_js(g_node_nth_child(ast,0));
				genere_code_js(g_node_nth_child(ast,1));
				break;
			case SI:
				fprintf(fichier,"\tif(");
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier,"){\n");
				genere_code_js(g_node_nth_child(ast,1));
				fprintf(fichier,"\t}");
				break;
			case SINON:
				fprintf(fichier,"else{\n");
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier,"\t}\n");
				break;
			case BOUCLE_FOR:
				fprintf(fichier,"\tvar i%i;\n\tfor(i%i=",nb_boucle,nb_boucle);
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier,";i%i<",nb_boucle);
				genere_code_js(g_node_nth_child(ast,2));
				fprintf(fichier,";i%i+=",nb_boucle);
				genere_code_js(g_node_nth_child(ast,1));
				fprintf(fichier,"){\n");
				nb_boucle++;
				genere_code_js(g_node_nth_child(ast,3));
				fprintf(fichier,"\t}\n");
				break;
			case BOUCLE_WHILE:
				fprintf(fichier,"\twhile(");
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier,"){\n");
				genere_code_js(g_node_nth_child(ast,1));
				fprintf(fichier,"\t}\n");
				break;
			case BOUCLE_DO_WHILE:
				fprintf(fichier,"\tdo{\n");
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier,"\t}while(");
				genere_code_js(g_node_nth_child(ast,1));
				fprintf(fichier,");\n");
				break;
			case BLOC_CODE:
				genere_code_js(g_node_nth_child(ast,0));
				break;
			case AFFICHAGET:
				fprintf(fichier,"\tconsole.log(");
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier,");\n");
				break;
			case TEXTE:
				fprintf(fichier,(char*)g_node_nth_child(ast,0)->data);
				break;
			case AFFECTATIONNT:
				fprintf(fichier,"\tvar ");
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier,"=");
				genere_code_js(g_node_nth_child(ast,1));
				fprintf(fichier,";\n");
				fprintf(fichier,"\tif(");
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier,"==null){\n");
				fprintf(fichier,"\tconsole.log(\"\\033[31m\\033[01mERREUR\\033[0m d'allocation memoire sur la variable ");
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier," !\");}");
				break;
			case AFFECTATIONT:
				fprintf(fichier,"\t");
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier,"=");
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier,"\tif(");
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier,"==null){\n");
				fprintf(fichier,"\tconsole.log(\"\\033[31m\\033[01mERREUR\\033[0m de reallocation memoire sur la variable ");
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier," !\");}");
				break;
			case SUPPRESSIONT:
				fprintf(fichier,"\t// 'del' is not available in JS\n");
				break;
			case AFFECTATIONT_CONCAT:
				fprintf(fichier,"\t// 'concat' is not available in JS\n");
				/*genere_code_js(g_node_nth_child(ast,0));
				genere_code_js(g_node_nth_child(ast,1));*/
				break;
			case DECIMAL:
				fprintf(fichier,(char*)g_node_nth_child(ast,0)->data);
				break;
			case AFFECTATIOND:
				fprintf(fichier,"\tvar ");
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier,"=");
				genere_code_js(g_node_nth_child(ast,1));
				fprintf(fichier,";\n");
				break;
			case AFFICHAGED:
				fprintf(fichier,"\tconsole.log(");
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier,");\n");
				break;
			case SAISIENT:
				/*fprintf(fichier,"\tvar ");
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier,";\n\tif((");
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier,"=malloc(");
				fprintf(fichier,"sizeof(char)))==null){\n");
				fprintf(fichier,"\tconsole.log(\"\\033[31m\\033[01mERREUR\\033[0m de reallocation memoire sur la variable ");
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier," !\");\n\texit(-1);\n\t}\n");
				fprintf(fichier,"\t_esaisie=0;\n");
				fprintf(fichier,"\tdo{\n");
				fprintf(fichier,"\t_csaisie=getchar();\n\t");
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier,"[_esaisie]=_csaisie;\n");
				fprintf(fichier,"\tif((");
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier,"=realloc(");
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier,",sizeof(char)*(_esaisie+2)))==null){\n");
				fprintf(fichier,"\tprintf(\"\\033[31m\\033[01mERREUR\\033[0m de reallocation memoire sur la variable ");
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier," !\");\n\texit(-1);\n\t}\n");
				fprintf(fichier,"\t_esaisie++;\n");
				fprintf(fichier,"\t}while(_csaisie!='\\n');\n");
				fprintf(fichier,"\t");
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier,"[_esaisie-1]='\\0';\n");*/
				break;
			case SAISIET:
				/*fprintf(fichier,"\tif((");
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier,"=realloc(");
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier,",sizeof(char)))==null){\n");
				fprintf(fichier,"\tprintf(\"\\033[31m\\033[01mERREUR\\033[0m de reallocation memoire sur la variable ");
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier," !\");\n\texit(-1);\n\t}\n");
				fprintf(fichier,"\t_esaisie=0;\n");
				fprintf(fichier,"\tdo{\n");
				fprintf(fichier,"\t_csaisie=getchar();\n\t");
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier,"[_esaisie]=_csaisie;\n");
				fprintf(fichier,"\tif((");
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier,"=realloc(");
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier,",sizeof(char)*(_esaisie+2)))==null){\n");
				fprintf(fichier,"\tprintf(\"\\033[31m\\033[01mERREUR\\033[0m de reallocation memoire sur la variable ");
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier," !\");\n\texit(-1);\n\t}\n");
				fprintf(fichier,"\t_esaisie++;\n");
				fprintf(fichier,"\t}while(_csaisie!='\\n');\n");
				fprintf(fichier,"\t");
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier,"[_esaisie-1]='\\0';\n");*/
				break;
			case SAISIENE:
				/*fprintf(fichier,"\tif((_tsaisie");
				fprintf(fichier,"=malloc(");
				fprintf(fichier,"sizeof(char)))==null){\n");
				fprintf(fichier,"\tprintf(\"\\033[31m\\033[01mERREUR\\033[0m de reallocation memoire sur la variable ");
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier," !\");\n\texit(-1);\n\t}\n");
				fprintf(fichier,"\t_esaisie=0;\n");
				fprintf(fichier,"\tdo{\n");
				fprintf(fichier,"\t_csaisie=getchar();\n");
				fprintf(fichier,"\t_tsaisie[_esaisie]=_csaisie;\n");
				fprintf(fichier,"\tif((_tsaisie");
				fprintf(fichier,"=realloc(_tsaisie");
				fprintf(fichier,",sizeof(char)*(_esaisie+2)))==null){\n");
				fprintf(fichier,"\tprintf(\"\\033[31m\\033[01mERREUR\\033[0m de reallocation memoire sur la variable ");
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier," !\");\n\texit(-1);\n\t}\n");
				fprintf(fichier,"\t_esaisie++;\n");
				fprintf(fichier,"\t}while(_csaisie!='\\n');\n");
				fprintf(fichier,"\t_tsaisie");
				fprintf(fichier,"[_esaisie-1]='\\0';\n");
				fprintf(fichier,"\tlong ");
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier,"=strtold(_tsaisie,null);\n\tfree(_tsaisie);\n");*/
				break;
			case SAISIEE:
				/*fprintf(fichier,"\tif((_tsaisie");
				fprintf(fichier,"=malloc(");
				fprintf(fichier,"sizeof(char)))==null){\n");
				fprintf(fichier,"\tprintf(\"\\033[31m\\033[01mERREUR\\033[0m de reallocation memoire sur la variable ");
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier," !\");\n\texit(-1);\n\t}\n");
				fprintf(fichier,"\t_esaisie=0;\n");
				fprintf(fichier,"\tdo{\n");
				fprintf(fichier,"\t_csaisie=getchar();\n");
				fprintf(fichier,"\t_tsaisie[_esaisie]=_csaisie;\n");
				fprintf(fichier,"\tif((_tsaisie");
				fprintf(fichier,"=realloc(_tsaisie");
				fprintf(fichier,",sizeof(char)*(_esaisie+2)))==null){\n");
				fprintf(fichier,"\tprintf(\"\\033[31m\\033[01mERREUR\\033[0m de reallocation memoire sur la variable ");
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier," !\");\n\texit(-1);\n\t}\n");
				fprintf(fichier,"\t_esaisie++;\n");
				fprintf(fichier,"\t}while(_csaisie!='\\n');\n");
				fprintf(fichier,"\t_tsaisie[_esaisie-1]='\\0';\n\t");
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier,"=strtold(_tsaisie,null);\n\tfree(_tsaisie);\n");*/
				break;
			case SAISIENB:
				/*fprintf(fichier,"\tif((_tsaisie");
				fprintf(fichier,"=malloc(");
				fprintf(fichier,"sizeof(char)))==null){\n");
				fprintf(fichier,"\tprintf(\"\\033[31m\\033[01mERREUR\\033[0m de reallocation memoire sur la variable ");
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier," !\");\n\texit(-1);\n\t}\n");
				fprintf(fichier,"\t_esaisie=0;\n");
				fprintf(fichier,"\tdo{\n");
				fprintf(fichier,"\t_csaisie=getchar();\n");
				fprintf(fichier,"\t_tsaisie[_esaisie]=_csaisie;\n");
				fprintf(fichier,"\tif((_tsaisie");
				fprintf(fichier,"=realloc(_tsaisie");
				fprintf(fichier,",sizeof(char)*(_esaisie+2)))==null){\n");
				fprintf(fichier,"\tprintf(\"\\033[31m\\033[01mERREUR\\033[0m de reallocation memoire sur la variable ");
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier," !\");\n\texit(-1);\n\t}\n");
				fprintf(fichier,"\t_esaisie++;\n");
				fprintf(fichier,"\t}while(_csaisie!='\\n');\n");
				fprintf(fichier,"\t_tsaisie");
				fprintf(fichier,"[_esaisie-1]='\\0';\n");
				fprintf(fichier,"\tbool ");
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier,"=(strcmp(_tsaisie,\"vrai\")==0||strcmp(_tsaisie,\"true\")==0||strcmp(_tsaisie,\"1\")==0);\n\tfree(_tsaisie);\n");*/
				break;
			case SAISIEB:
				/*fprintf(fichier,"\tif((_tsaisie");
				fprintf(fichier,"=malloc(");
				fprintf(fichier,"sizeof(char)))==null){\n");
				fprintf(fichier,"\tprintf(\"\\033[31m\\033[01mERREUR\\033[0m de reallocation memoire sur la variable ");
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier," !\");\n\texit(-1);\n\t}\n");
				fprintf(fichier,"\t_esaisie=0;\n");
				fprintf(fichier,"\tdo{\n");
				fprintf(fichier,"\t_csaisie=getchar();\n");
				fprintf(fichier,"\t_tsaisie[_esaisie]=_csaisie;\n");
				fprintf(fichier,"\tif((_tsaisie");
				fprintf(fichier,"=realloc(_tsaisie");
				fprintf(fichier,",sizeof(char)*(_esaisie+2)))==null){\n");
				fprintf(fichier,"\tprintf(\"\\033[31m\\033[01mERREUR\\033[0m de reallocation memoire sur la variable ");
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier," !\");\n\texit(-1);\n\t}\n");
				fprintf(fichier,"\t_esaisie++;\n");
				fprintf(fichier,"\t}while(_csaisie!='\\n');\n");
				fprintf(fichier,"\t_tsaisie");
				fprintf(fichier,"[_esaisie-1]='\\0';\n\t");
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier,"=(strcmp(_tsaisie,\"vrai\")==0||strcmp(_tsaisie,\"true\")==0||strcmp(_tsaisie,\"1\")==0);\n\tfree(_tsaisie);\n");*/
				break;
			case SAISIEND:
				/*fprintf(fichier,"\tif((_tsaisie");
				fprintf(fichier,"=malloc(");
				fprintf(fichier,"sizeof(char)))==null){\n");
				fprintf(fichier,"\tprintf(\"\\033[31m\\033[01mERREUR\\033[0m de reallocation memoire sur la variable ");
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier," !\");\n\texit(-1);\n\t}\n");
				fprintf(fichier,"\t_esaisie=0;\n");
				fprintf(fichier,"\tdo{\n");
				fprintf(fichier,"\t_csaisie=getchar();\n");
				fprintf(fichier,"\t_tsaisie[_esaisie]=_csaisie;\n");
				fprintf(fichier,"\tif((_tsaisie");
				fprintf(fichier,"=realloc(_tsaisie");
				fprintf(fichier,",sizeof(char)*(_esaisie+2)))==null){\n");
				fprintf(fichier,"\tprintf(\"\\033[31m\\033[01mERREUR\\033[0m de reallocation memoire sur la variable ");
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier," !\");\n\texit(-1);\n\t}\n");
				fprintf(fichier,"\t_esaisie++;\n");
				fprintf(fichier,"\t}while(_csaisie!='\\n');\n");
				fprintf(fichier,"\t_tsaisie");
				fprintf(fichier,"[_esaisie-1]='\\0';\n");
				fprintf(fichier,"\tdouble ");
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier,"=strtod(_tsaisie,null);\n\tfree(_tsaisie);\n");*/
				break;
			case SAISIED:
				/*fprintf(fichier,"\tif((_tsaisie");
				fprintf(fichier,"=malloc(");
				fprintf(fichier,"sizeof(char)))==null){\n");
				fprintf(fichier,"\tprintf(\"\\033[31m\\033[01mERREUR\\033[0m de reallocation memoire sur la variable ");
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier," !\");\n\texit(-1);\n\t}\n");
				fprintf(fichier,"\t_esaisie=0;\n");
				fprintf(fichier,"\tdo{\n");
				fprintf(fichier,"\t_csaisie=getchar();\n");
				fprintf(fichier,"\t_tsaisie[_esaisie]=_csaisie;\n");
				fprintf(fichier,"\tif((_tsaisie");
				fprintf(fichier,"=realloc(_tsaisie");
				fprintf(fichier,",sizeof(char)*(_esaisie+2)))==null){\n");
				fprintf(fichier,"\tprintf(\"\\033[31m\\033[01mERREUR\\033[0m de reallocation memoire sur la variable ");
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier," !\");\n\texit(-1);\n\t}\n");
				fprintf(fichier,"\t_esaisie++;\n");
				fprintf(fichier,"\t}while(_csaisie!='\\n');\n");
				fprintf(fichier,"\t_tsaisie[_esaisie-1]='\\0';\n\t");
				genere_code_js(g_node_nth_child(ast,0));
				fprintf(fichier,"=strtod(_tsaisie,null);\n\tfree(_tsaisie);\n");*/
				break;
			/*default:
				fprintf(fichier,"// Error");*/
		}
	}
}
